authors/urls.py
from django.urls import path

from . import views

app_name = 'authors'

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('register/create/', views.register_create, name='register_create'),
    path('login/', views.login_view, name='login'),
    path('login/create/', views.login_create, name='login_create'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/recipe/<int:id>/edit/', views.DashboardRecipe.as_view(), name='dashboard_recipe_edit'),
    path('dashboard/recipe/new/', views.DashboardRecipe.as_view(), name='dashboard_recipe_new'),
    path('dashboard/recipe/delete/', views.DashboardRecipeDelete.as_view(), name='dashboard_recipe_delete'),
    path('profile/<int:id>/', views.ProfileView.as_view(), name='profile'),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include('recipes.urls')),
    path('authors/',include('authors.urls')),
    ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

projeto/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include('recipes.urls'))
    ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recipes/urls.py
from django.urls import path

from . import views

app_name = 'recipes'

urlpatterns = [
    path('', views.RecipeListViewHome.as_view(), name="home"),
    path('recipes/search/', views.RecipeListViewSearch.as_view(), name="search"),
    path('recipes/category/<int:category_id>/',views.RecipeListViewCategory.as_view(), name="category"),
    path('recipes/<int:pk>/', views.RecipeDetail.as_view(), name="recipe"),
    path('recipes/theory/', views.theory, name='theory')
]

recipes/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
import os
from django.conf import settings
from PIL import Image

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=65)
    
    def __str__(self):
        return self.name

class Recipe(models.Model):
    title = models.CharField(max_length=65)
    description = models.CharField(max_length=165)
    slug = models.SlugField(unique=True)
    preparation_time = models.IntegerField()
    preparation_time_unit = models.CharField(max_length=65)
    servings = models.IntegerField()
    servings_unit = models.CharField(max_length=65)
    preparation_steps = models.TextField()
    preparation_steps_is_html = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(upload_to='recipes/covers/%Y/%m/%d/', blank=True, default='')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True, default=None)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("recipes:recipe", args=(self.id,))
    
    @staticmethod
    def resize_image(image, new_width=800):
        image_full_path = os.path.join(settings.MEDIA_ROOT, image.name)
        image_pillow = Image.open(image_full_path)
        original_width, original_height = image_pillow.size
        
        if original_width <= new_width:
            image_pillow.close()
            return
        
        new_height = round((new_width * original_height) / original_width)
        
        new_image = image_pillow.resize((new_width, new_height), Image.LANCZOS)
        
        new_image.save(image_full_path, optimize=True, quality=50,)
            
    
    def save(self, *args, **kwargs):
        if not self.slug:
            slug = f'{slugify(self.title)}'
            self.slug = slug
            
        saved = super().save(*args, **kwargs)
        
        if self.cover:
            try:
                self.resize_image(self.cover, 840)
            except FileNotFoundError:
                ...
        
        return saved
    

authors/forms/recipe_form.py
from collections import defaultdict

from django import forms
from django.core.exceptions import ValidationError

from recipes.models import Recipe
from utils.django_forms import add_attr
from utils.strings import is_positive_number


class AuthorRecipeForm(forms.ModelForm):
    def __init__(self,*args, **kwargs):
        super().__init__(*args, **kwargs)
        
        self._my_errors = defaultdict(list)
        
        add_attr(self.fields.get('preparation_steps'), 'class', 'span-2')
        
    
    class Meta:
        model = Recipe
        fields = 'title', 'description', 'preparation_time',\
            'preparation_time_unit', 'servings', 'servings_unit',\
                'preparation_steps', 'cover'
        widgets = { 
                   'cover':forms.FileInput(attrs={'class':'span-2'}),
                   'servings_unit':forms.Select(choices=(
                                                ('Porções','Porções'),
                                                ('Pedaços','Pedaços'),
                                                ('Pessoas','Pessoas'),),
                                                ),
                   'preparation_time_unit':forms.Select(choices=(
                                                ('Minutos','Minutos'),
                                                ('Horas','Horas'),),
                                                )
                   }
    def clean(self, *args, **kwargs):
        super_clean = super().clean(*args, **kwargs)
        cd = self.cleaned_data

        title = cd.get('title')
        description = cd.get('description')

        if title == description:
            self._my_errors['title'].append('Cannot be equal to description')
            self._my_errors['description'].append('Cannot be equal to title')

        if self._my_errors:
            raise ValidationError(self._my_errors)

        return super_clean

    def clean_title(self):
        title = self.cleaned_data.get('title')

        if len(title) < 5:
            self._my_errors['title'].append('Must have at least 5 chars.')

        return title

    def clean_preparation_time(self):
        field_name = 'preparation_time'
        field_value = self.cleaned_data.get(field_name)

        if not is_positive_number(field_value):
            self._my_errors[field_name].append('Must be a positive number')

        return field_value

    def clean_servings(self):
        field_name = 'servings'
        field_value = self.cleaned_data.get(field_name)

        if not is_positive_number(field_value):
            self._my_errors[field_name].append('Must be a positive number')

        return field_value

recipes/views.py
import os

from django.db.models import Q
from django.http.response import Http404
from django.views.generic import DetailView, ListView
from utils.recipes.pagination import make_pagination
from recipes.models import Recipe
from django.shortcuts import render

PER_PAGE = int(os.environ.get('PER_PAGE', 6))


def theory(request,*args, **kwargs):
    recipes = Recipe.objects.all()
    
    recipes = recipes.exclude(title__iexact='Título aleatório')
    
    context = {
        'recipes':recipes
        }
      
    
    return render(request,'recipes/pages/theory.html', context=context)


class RecipeListViewBase(ListView):
    model = Recipe
    context_object_name = 'recipes'
    ordering = ['-id']
    template_name = 'recipes/pages/home.html'

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(
            is_published=True,
        )
        qs = qs.select_related('author', 'category')
        qs = qs.prefetch_related('author__profile')
        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        page_obj, pagination_range = make_pagination(
            self.request,
            ctx.get('recipes'),
            PER_PAGE
        )
        ctx.update(
            {'recipes': page_obj, 'pagination_range': pagination_range}
        )
        return ctx


class RecipeListViewHome(RecipeListViewBase):
    template_name = 'recipes/pages/home.html'


class RecipeListViewCategory(RecipeListViewBase):
    template_name = 'recipes/pages/category.html'

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)

        ctx.update({
            'title': f'{ctx.get("recipes")[0].category.name} - Category | '
        })

        return ctx

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(
            category__id=self.kwargs.get('category_id')
        )

        if not qs:
            raise Http404()

        return qs


class RecipeListViewSearch(RecipeListViewBase):
    template_name = 'recipes/pages/search.html'

    def get_queryset(self, *args, **kwargs):
        search_term = self.request.GET.get('q', '')

        if not search_term:
            raise Http404()

        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(
            Q(
                Q(title__icontains=search_term) |
                Q(description__icontains=search_term),
            )
        )
        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        search_term = self.request.GET.get('q', '')

        ctx.update({
            'page_title': f'Search for "{search_term}" |',
            'search_term': search_term,
            'additional_url_query': f'&q={search_term}',
        })

        return ctx


class RecipeDetail(DetailView):
    model = Recipe
    context_object_name = 'recipe'
    template_name = 'recipes/pages/recipe-view.html'

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(is_published=True)
        return qs
    
    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)

        ctx.update({
            'is_detail_page': True
        })

        return ctx

recipes/templates/recipes/partials/head.html
{% load static %}

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/fontawesome.min.css"
    integrity="sha512-v8QQ0YQ3H4K6Ic3PJkym91KoeNT5S3PnDKvqnwqFD1oiqIl653crGZplPdU5KKtHjO0QKcQ2aUlQZYjHczkmGw=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/brands.min.css"
    integrity="sha512-58P9Hy7II0YeXLv+iFiLCv1rtLW47xmiRpC1oFafeKNShp8V5bKV/ciVtYqbk2YfxXQMt58DjNfkXFOn62xE+g=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/solid.min.css"
    integrity="sha512-DzC7h7+bDlpXPDQsX/0fShhf1dLxXlHuhPBkBo/5wJWRoTU6YL7moeiNoej6q3wh5ti78C57Tu1JwTNlcgHSjg=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">


<link rel="stylesheet" href="{%  static 'recipes/css/styles.css' %}">

recipes/templates/recipes/partials/recipe.html
<div class="recipe recipe-list-item">
    
    {% if recipe.cover %}
        <div class="recipe-cover">
            <a href="{{ recipe.get_absolute_url }}">
                <img src="{{ recipe.cover.url }}" alt="Temporário">
            </a>
        </div>
    {% endif %}

    <div class="recipe-title-container">
        <h2 class="recipe-title">
            <a href="{{ recipe.get_absolute_url }}">
                {{ recipe.title }}
            </a>
        </h2>
    </div>

    <div class="recipe-author">
        <span class="recipe-author-item">
            {% if recipe.author.profile %}
                <a href="{% url 'authors:profile' recipe.author.profile.id %}">
            {% endif %}

            <i class="fas fa-user"></i>

            {% if recipe.author.first_name %}

                {{recipe.author.first_name}} {{recipe.author.last_name}}

            {% else %}

                {{recipe.author.username}}

            {% endif %}

            {% if recipe.author.profile %}
                </a>
            {% endif %}

        </span>
        <span class="recipe-author-item">
            <i class="fas fa-calendar-alt"></i>
            {{recipe.created_at|date:"d/m/Y"}} às {{recipe.created_at|date:"H:i:s"}}
        </span>
        {% if recipe.category is not None %}
            <span class="recipe-author-item">
                <a href="{% url "recipes:category" recipe.category.id %}">
                    <i class="fas fa-layer-group"></i>
                    <span>{{recipe.category.name}}</span>
                </a>
            </span>
        {% endif %}
    </div>

    <div class="recipe-content">
        <p>{{recipe.description}}</p>
    </div>

    <div class="recipe-meta-container">
        <div class="recipe-meta recipe-preparation">
            <h3 class="recipe-meta-title"><i class="fas fa-stopwatch"></i> Preparo</h3>
            <div class="recipe-meta-text">
                {{recipe.preparation_time}} {{recipe.preparation_time_unit}}
            </div>
        </div>
        <div class="recipe-meta recipe-servings">
            <h3 class="recipe-meta-title"><i class="fas fa-pizza-slice"></i> Porções</h3>
            <div class="recipe-meta-text">
                {{recipe.servings}} {{recipe.servings_unit}}
            </div>
        </div>
    </div>

    {% if is_detail_page is not True %}
    
        <footer class="recipe-footer">
            <a class="recipe-read-more button button-dark button-full-width" href="{% url 'recipes:recipe' recipe.id %}">
                <i class="fas fa-eye"></i>
                <span>ver mais...</span>
            </a>
        </footer>

    {% endif %}

    {% if is_detail_page is True %}
        <div class="preparation-steps">

            {% if recipe.preparation_steps_is_html is True %}
                {{ recipe.preparation_steps|safe }}
            {% else %}
                {{ recipe.preparation_steps|linebreaksbr }}
            {% endif %}

        </div>
    {% endif %}



</div>